version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV} # Changed from 'production' to ${NODE_ENV}
    # Optional: Add this for Linux compatibility
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  frontend:
    build: ./frontend
    ports:
      - '5173:80'
